version: "3.8"

networks:
  global:
    external: true

services:
  grafana:
    image: grafana/grafana:9.2.15
    restart: always
    ulimits:
      nofile: 262144
    networks:
      - global
    ports:
      - "3000:3000"
    volumes:
      - ${DATA_DIR}/grafana/lib/:/var/lib/grafana/
      - ${DATA_DIR}/grafana/etc/:/etc/grafana/
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
