version: "3.8"

networks:
  global:
    driver: overlay

services:
  mariadb:
    image: mariadb:10.10.2
    environment:
      MARIADB_ROOT_PASSWORD: root
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - /data/stack/mysql/:/var/lib/mysql/
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone

