version: "3.8"

networks:
  global:
    driver: overlay
    name: global

services:
  mariadb:
    image: mariadb:10.10.2
    environment:
      MARIADB_ROOT_PASSWORD: root
    restart: always
    networks:
      - global
    ports:
      - "3306:3306"
    volumes:
      - ${DATA_DIR}/mysql/:/var/lib/mysql/
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone

