version: "3.8"

networks:
  global:
    driver: overlay
    name: global

services:
  mongo:
    image: mongo:6.0.3
    restart: always
    networks:
      - global
    ports:
      - "27017:27017"
      - "28017:28017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - ${DATA_DIR}/mongo/:/data/
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone

  mongo-express:
    image: mongo-express:latest
    restart: always
    networks:
      - global
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
      ME_CONFIG_MONGODB_URL: mongodb://mongo:mongo@mongo:27017/
    depends_on:
      - mongo
