version: "3.8"

networks:
  global:
    driver: overlay

services:
  postgres:
    image: postgres:15.1-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - /data/stack/postgres/:/var/lib/postgresql/data/
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
