version: "3.8"

networks:
  global:
    driver: overlay
    name: global

services:
  postgres:
    image: postgres:15.1-alpine
    restart: always
    networks:
      - global
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ${DATA_DIR}/postgres/:/var/lib/postgresql/data/
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
