version: "3.8"

networks:
  global:
    external: true

services:
  postgres:
    image: influxdb:2.7.1-alpine
    restart: always
    networks:
      - global
    ports:
      - "8086:8086"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ${DATA_DIR}/influxdb/:/var/lib/influxdb2/
      - ${DATA_DIR}/ifx_etc/:/etc/influxdb2/
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
