version: "3.8"

networks:
  global:
    external: true

services:
  redis:
    image: redis:7.0.7-alpine
    restart: always
    command:
      - "redis-server"
      - "--save"
      - "60"
      - "1"
      - "--loglevel"
      - "warning"
      - "--requirepass"
      - "redis"
      - "--bind"
      - "0.0.0.0"
    ports:
      - "6379:6379"
    networks:
      - global
    volumes:
      - ${DATA_DIR}/redis/:/data/
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
